# Note, you need to set sudo sysctl -w vm.max_map_count=262144
# for running elk on linux
version: '2'
services:
  api:
    image: opendatagateway/api:latest
    ports:
      - "8080:8080"
    links:
      - elasticsearch
  ir:
    image: opendatagateway/information_retrieval:latest
    links:
      - elasticsearch
  elasticsearch:
    image: elasticsearch
    ports:
      - "9200:9200"
      - "9300:9300"
