# Note, you need to set sudo sysctl -w vm.max_map_count=262144
# for running elk on linux
version: '2.1'
services:
  api:
    image: opendatagateway/api:latest
    ports:
      - "8080:8080"
    depends_on:
      elasticsearch:
        condition: service_healthy
    links:
      - elasticsearch

  ir:
    image: opendatagateway/information_retrieval:latest
    depends_on:
          elasticsearch:
            condition: service_healthy
    links:
      - elasticsearch

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.2.2
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    mem_limit: 1g
    cap_add:
      - IPC_LOCK
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:9200"]
            interval: 30s
            timeout: 10s
            retries: 5
