# Note, you need to set sudo sysctl -w vm.max_map_count=262144
# for running elk on linux
version: '2'
services:
  api:
    image: opendatagateway/api:latest
    ports:
      - "8090:8090"
  ir:
    image: opendatagateway/informationretrieval:latest
    ports:
      - "8080:8080"
    links:
      - elk
  elk:
    image: sebp/elk
    ports:
    - "5601:5601"
    - "5044:5044"
