/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'joek0073' at '2017-03-10 14:53' with Gradle 2.10
 *
 * @author joek0073, @date 2017-03-10 14:53
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
